<?php

use Illuminate\Database\Seeder;

class BanksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if(!\App\Models\Bank::first()){
            DB::table('banks')->insert([
                ['code' => '654', 'name' => 'Banco A.J.Renner S.A.', 'main' => 0],
                ['code' => '246', 'name' => 'Banco ABC Brasil S.A.', 'main' => 0],
                ['code' => '025', 'name' => 'Banco Alfa S.A.', 'main' => 0],
                ['code' => '641', 'name' => 'Banco Alvorada S.A.', 'main' => 0],
                ['code' => '213', 'name' => 'Banco Arbi S.A.', 'main' => 0],
                ['code' => '019', 'name' => 'Banco Azteca do Brasil S.A.', 'main' => 0],
                ['code' => '029', 'name' => 'Banco Banerj S.A.', 'main' => 0],
                ['code' => '000', 'name' => 'Banco Bankpar S.A.', 'main' => 0],
                ['code' => '740', 'name' => 'Banco Barclays S.A.', 'main' => 0],
                ['code' => '107', 'name' => 'Banco BBM S.A.', 'main' => 0],
                ['code' => '031', 'name' => 'Banco Beg S.A.', 'main' => 0],
                ['code' => '739', 'name' => 'Banco BGN S.A.', 'main' => 0],
                ['code' => '096', 'name' => 'Banco BM&F de Serviços de Liquidação e Custódia S.A', 'main' => 0],
                ['code' => '318', 'name' => 'Banco BMG S.A.', 'main' => 0],
                ['code' => '752', 'name' => 'Banco BNP Paribas Brasil S.A.', 'main' => 0],
                ['code' => '248', 'name' => 'Banco Boavista Interatlântico S.A.', 'main' => 0],
                ['code' => '218', 'name' => 'Banco Bonsucesso S.A.', 'main' => 0],
                ['code' => '065', 'name' => 'Banco Bracce S.A.', 'main' => 0],
                ['code' => '036', 'name' => 'Banco Bradesco BBI S.A.', 'main' => 0],
                ['code' => '204', 'name' => 'Banco Bradesco Cartões S.A.', 'main' => 0],
                ['code' => '394', 'name' => 'Banco Bradesco Financiamentos S.A.', 'main' => 0],
                ['code' => '237', 'name' => 'Banco Bradesco S.A.', 'main' => 1],
                ['code' => '225', 'name' => 'Banco Brascan S.A.', 'main' => 0],
                ['code' => 'M15', 'name' => 'Banco BRJ S.A.', 'main' => 0],
                ['code' => '208', 'name' => 'Banco BTG Pactual S.A.', 'main' => 0],
                ['code' => '044', 'name' => 'Banco BVA S.A.', 'main' => 0],
                ['code' => '263', 'name' => 'Banco Cacique S.A.', 'main' => 0],
                ['code' => '473', 'name' => 'Banco Caixa Geral - Brasil S.A.', 'main' => 0],
                ['code' => '412', 'name' => 'Banco Capital S.A.', 'main' => 0],
                ['code' => '040', 'name' => 'Banco Cargill S.A.', 'main' => 0],
                ['code' => '745', 'name' => 'Banco Citibank S.A.', 'main' => 0],
                ['code' => 'M08', 'name' => 'Banco Citicard S.A.', 'main' => 0],
                ['code' => '241', 'name' => 'Banco Clássico S.A.', 'main' => 0],
                ['code' => 'M19', 'name' => 'Banco CNH Capital S.A.', 'main' => 0],
                ['code' => '215', 'name' => 'Banco Comercial e de Investimento Sudameris S.A.', 'main' => 0],
                ['code' => '756', 'name' => 'Banco Cooperativo do Brasil S.A. - BANCOOB', 'main' => 0],
                ['code' => '748', 'name' => 'Banco Cooperativo Sicredi S.A.', 'main' => 0],
                ['code' => '075', 'name' => 'Banco CR2 S.A.', 'main' => 0],
                ['code' => '721', 'name' => 'Banco Credibel S.A.', 'main' => 0],
                ['code' => '222', 'name' => 'Banco Credit Agricole Brasil S.A.', 'main' => 0],
                ['code' => '505', 'name' => 'Banco Credit Suisse (Brasil) S.A.', 'main' => 0],
                ['code' => '229', 'name' => 'Banco Cruzeiro do Sul S.A.', 'main' => 0],
                ['code' => '266', 'name' => 'Banco Cédula S.A.', 'main' => 0],
                ['code' => '003', 'name' => 'Banco da Amazônia S.A.', 'main' => 0],
                ['code' => '083-3', 'name' => 'Banco da China Brasil S.A.', 'main' => 0],
                ['code' => 'M21', 'name' => 'Banco Daimlerchrysler S.A.', 'main' => 0],
                ['code' => '707', 'name' => 'Banco Daycoval S.A.', 'main' => 0],
                ['code' => '300', 'name' => 'Banco de La Nacion Argentina', 'main' => 0],
                ['code' => '495', 'name' => 'Banco de La Provincia de Buenos Aires', 'main' => 0],
                ['code' => '494', 'name' => 'Banco de La Republica Oriental del Uruguay', 'main' => 0],
                ['code' => 'M06', 'name' => 'Banco de Lage Landen Brasil S.A.', 'main' => 0],
                ['code' => '024', 'name' => 'Banco de Pernambuco S.A. - BANDEPE', 'main' => 0],
                ['code' => '456', 'name' => 'Banco de Tokyo-Mitsubishi UFJ Brasil S.A.', 'main' => 0],
                ['code' => '214', 'name' => 'Banco Dibens S.A.', 'main' => 0],
                ['code' => '001', 'name' => 'Banco do Brasil S.A.', 'main' => 1],
                ['code' => '047', 'name' => 'Banco do Estado de Sergipe S.A.', 'main' => 0],
                ['code' => '037', 'name' => 'Banco do Estado do Pará S.A.', 'main' => 0],
                ['code' => '039', 'name' => 'Banco do Estado do Piauí S.A. - BEP', 'main' => 0],
                ['code' => '041', 'name' => 'Banco do Estado do Rio Grande do Sul S.A.', 'main' => 0],
                ['code' => '004', 'name' => 'Banco do Nordeste do Brasil S.A.', 'main' => 0],
                ['code' => '265', 'name' => 'Banco Fator S.A.', 'main' => 0],
                ['code' => 'M03', 'name' => 'Banco Fiat S.A.', 'main' => 0],
                ['code' => '224', 'name' => 'Banco Fibra S.A.', 'main' => 0],
                ['code' => '626', 'name' => 'Banco Ficsa S.A.', 'main' => 0],
                ['code' => 'M18', 'name' => 'Banco Ford S.A.', 'main' => 0],
                ['code' => '233', 'name' => 'Banco GE Capital S.A.', 'main' => 0],
                ['code' => '734', 'name' => 'Banco Gerdau S.A.', 'main' => 0],
                ['code' => 'M07', 'name' => 'Banco GMAC S.A.', 'main' => 0],
                ['code' => '612', 'name' => 'Banco Guanabara S.A.', 'main' => 0],
                ['code' => 'M22', 'name' => 'Banco Honda S.A.', 'main' => 0],
                ['code' => '063', 'name' => 'Banco Ibi S.A. Banco Múltiplo', 'main' => 0],
                ['code' => 'M11', 'name' => 'Banco IBM S.A.', 'main' => 0],
                ['code' => '604', 'name' => 'Banco Industrial do Brasil S.A.', 'main' => 0],
                ['code' => '320', 'name' => 'Banco Industrial e Comercial S.A.', 'main' => 0],
                ['code' => '653', 'name' => 'Banco Indusval S.A.', 'main' => 0],
                ['code' => '630', 'name' => 'Banco Intercap S.A.', 'main' => 0],
                ['code' => '249', 'name' => 'Banco Investcred Unibanco S.A.', 'main' => 0],
                ['code' => 'M09', 'name' => 'Banco Itaucred Financiamentos S.A.', 'main' => 0],
                ['code' => '184', 'name' => 'Banco Itaú BBA S.A.', 'main' => 0],
                ['code' => '479', 'name' => 'Banco ItaúBank S.A', 'main' => 0],
                ['code' => '376', 'name' => 'Banco J. P. Morgan S.A.', 'main' => 0],
                ['code' => '074', 'name' => 'Banco J. Safra S.A.', 'main' => 0],
                ['code' => '217', 'name' => 'Banco John Deere S.A.', 'main' => 0],
                ['code' => '076', 'name' => 'Banco KDB S.A.', 'main' => 0],
                ['code' => '757', 'name' => 'Banco KEB do Brasil S.A.', 'main' => 0],
                ['code' => '600', 'name' => 'Banco Luso Brasileiro S.A.', 'main' => 0],
                ['code' => '212', 'name' => 'Banco Matone S.A.', 'main' => 0],
                ['code' => 'M12', 'name' => 'Banco Maxinvest S.A.', 'main' => 0],
                ['code' => '389', 'name' => 'Banco Mercantil do Brasil S.A.', 'main' => 0],
                ['code' => '746', 'name' => 'Banco Modal S.A.', 'main' => 0],
                ['code' => 'M10', 'name' => 'Banco Moneo S.A.', 'main' => 0],
                ['code' => '738', 'name' => 'Banco Morada S.A.', 'main' => 0],
                ['code' => '066', 'name' => 'Banco Morgan Stanley S.A.', 'main' => 0],
                ['code' => '243', 'name' => 'Banco Máxima S.A.', 'main' => 0],
                ['code' => '045', 'name' => 'Banco Opportunity S.A.', 'main' => 0],
                ['code' => 'M17', 'name' => 'Banco Ourinvest S.A.', 'main' => 0],
                ['code' => '623', 'name' => 'Banco Panamericano S.A.', 'main' => 0],
                ['code' => '611', 'name' => 'Banco Paulista S.A.', 'main' => 0],
                ['code' => '613', 'name' => 'Banco Pecúnia S.A.', 'main' => 0],
                ['code' => '094-2', 'name' => 'Banco Petra S.A.', 'main' => 0],
                ['code' => '643', 'name' => 'Banco Pine S.A.', 'main' => 0],
                ['code' => '724', 'name' => 'Banco Porto Seguro S.A.', 'main' => 0],
                ['code' => '735', 'name' => 'Banco Pottencial S.A.', 'main' => 0],
                ['code' => '638', 'name' => 'Banco Prosper S.A.', 'main' => 0],
                ['code' => 'M24', 'name' => 'Banco PSA Finance Brasil S.A.', 'main' => 0],
                ['code' => '747', 'name' => 'Banco Rabobank International Brasil S.A.', 'main' => 0],
                ['code' => '088-4', 'name' => 'Banco Randon S.A.', 'main' => 0],
                ['code' => '356', 'name' => 'Banco Real S.A.', 'main' => 0],
                ['code' => '633', 'name' => 'Banco Rendimento S.A.', 'main' => 0],
                ['code' => '741', 'name' => 'Banco Ribeirão Preto S.A.', 'main' => 0],
                ['code' => 'M16', 'name' => 'Banco Rodobens S.A.', 'main' => 0],
                ['code' => '072', 'name' => 'Banco Rural Mais S.A.', 'main' => 0],
                ['code' => '453', 'name' => 'Banco Rural S.A.', 'main' => 0],
                ['code' => '422', 'name' => 'Banco Safra S.A.', 'main' => 0],
                ['code' => '033', 'name' => 'Banco Santander (Brasil) S.A.', 'main' => 1],
                ['code' => '250', 'name' => 'Banco Schahin S.A.', 'main' => 0],
                ['code' => '743', 'name' => 'Banco Semear S.A.', 'main' => 0],
                ['code' => '749', 'name' => 'Banco Simples S.A.', 'main' => 0],
                ['code' => '366', 'name' => 'Banco Société Générale Brasil S.A.', 'main' => 0],
                ['code' => '637', 'name' => 'Banco Sofisa S.A.', 'main' => 0],
                ['code' => '012', 'name' => 'Banco Standard de Investimentos S.A.', 'main' => 0],
                ['code' => '464', 'name' => 'Banco Sumitomo Mitsui Brasileiro S.A.', 'main' => 0],
                ['code' => '082-5', 'name' => 'Banco Topázio S.A.', 'main' => 0],
                ['code' => 'M20', 'name' => 'Banco Toyota do Brasil S.A.', 'main' => 0],
                ['code' => 'M13', 'name' => 'Banco Tricury S.A.', 'main' => 0],
                ['code' => '634', 'name' => 'Banco Triângulo S.A.', 'main' => 0],
                ['code' => 'M14', 'name' => 'Banco Volkswagen S.A.', 'main' => 0],
                ['code' => 'M23', 'name' => 'Banco Volvo (Brasil) S.A.', 'main' => 0],
                ['code' => '655', 'name' => 'Banco Votorantim S.A.', 'main' => 0],
                ['code' => '610', 'name' => 'Banco VR S.A.', 'main' => 0],
                ['code' => '370', 'name' => 'Banco WestLB do Brasil S.A.', 'main' => 0],
                ['code' => '021', 'name' => 'BANESTES S.A. Banco do Estado do Espírito Santo', 'main' => 0],
                ['code' => '719', 'name' => 'Banif-Banco Internacional do Funchal (Brasil)S.A.', 'main' => 0],
                ['code' => '755', 'name' => 'Bank of America Merrill Lynch Banco Múltiplo S.A.', 'main' => 0],
                ['code' => '744', 'name' => 'BankBoston N.A.', 'main' => 0],
                ['code' => '073', 'name' => 'BB Banco Popular do Brasil S.A.', 'main' => 0],
                ['code' => '078', 'name' => 'BES Investimento do Brasil S.A.-Banco de Investimento', 'main' => 0],
                ['code' => '069', 'name' => 'BPN Brasil Banco Múltiplo S.A.', 'main' => 0],
                ['code' => '070', 'name' => 'BRB - Banco de Brasília S.A.', 'main' => 0],
                ['code' => '092-2', 'name' => 'Brickell S.A. Crédito, financiamento e Investimento', 'main' => 0],
                ['code' => '104', 'name' => 'Caixa Econômica Federal', 'main' => 1],
                ['code' => '477', 'name' => 'Citibank N.A.', 'main' => 0],
                ['code' => '081-7', 'name' => 'Concórdia Banco S.A.', 'main' => 0],
                ['code' => '097-3', 'name' => 'Cooperativa Central de Crédito Noroeste Brasileiro Ltda.', 'main' => 0],
                ['code' => '085-x', 'name' => 'Cooperativa Central de Crédito Urbano-CECRED', 'main' => 0],
                ['code' => '099-x', 'name' => 'Cooperativa Central de Economia e Credito Mutuo das Unicreds', 'main' => 0],
                ['code' => '090-2', 'name' => 'Cooperativa Central de Economia e Crédito Mutuo das Unicreds', 'main' => 0],
                ['code' => '089-2', 'name' => 'Cooperativa de Crédito Rural da Região de Mogiana', 'main' => 0],
                ['code' => '087-6', 'name' => 'Cooperativa Unicred Central Santa Catarina', 'main' => 0],
                ['code' => '098-1', 'name' => 'Credicorol Cooperativa de Crédito Rural', 'main' => 0],
                ['code' => '487', 'name' => 'Deutsche Bank S.A. - Banco Alemão', 'main' => 0],
                ['code' => '751', 'name' => 'Dresdner Bank Brasil S.A. - Banco Múltiplo', 'main' => 0],
                ['code' => '064', 'name' => 'Goldman Sachs do Brasil Banco Múltiplo S.A.', 'main' => 0],
                ['code' => '062', 'name' => 'Hipercard Banco Múltiplo S.A.', 'main' => 0],
                ['code' => '399', 'name' => 'HSBC Bank Brasil S.A. - Banco Múltiplo', 'main' => 0],
                ['code' => '168', 'name' => 'HSBC Finance (Brasil) S.A. - Banco Múltiplo', 'main' => 0],
                ['code' => '492', 'name' => 'ING Bank N.V.', 'main' => 0],
                ['code' => '652', 'name' => 'Itaú Unibanco Holding S.A.', 'main' => 0],
                ['code' => '341', 'name' => 'Itaú Unibanco S.A.', 'main' => 1],
                ['code' => '079', 'name' => 'JBS Banco S.A.', 'main' => 0],
                ['code' => '488', 'name' => 'JPMorgan Chase Bank', 'main' => 0],
                ['code' => '014', 'name' => 'Natixis Brasil S.A. Banco Múltiplo', 'main' => 0],
                ['code' => '753', 'name' => 'NBC Bank Brasil S.A. - Banco Múltiplo', 'main' => 0],
                ['code' => '086-8', 'name' => 'OBOE Crédito Financiamento e Investimento S.A.', 'main' => 0],
                ['code' => '254', 'name' => 'Paraná Banco S.A.', 'main' => 0],
                ['code' => '409', 'name' => 'UNIBANCO - União de Bancos Brasileiros S.A.', 'main' => 0],
                ['code' => '230', 'name' => 'Unicard Banco Múltiplo S.A.', 'main' => 0],
                ['code' => '091-4', 'name' => 'Unicred Central do Rio Grande do Sul', 'main' => 0],
                ['code' => '084', 'name' => 'Unicred Norte do Paraná', 'main' => 0],
                ['code' => '260', 'name' => 'Nubank - Nu Pagamentos S.A', 'main' => 0],
                ['code' => '655', 'name' => 'Votorantim S.A', 'main' => 0],
                ['code' => '077', 'name' => 'Banco Intermedium S.A', 'main' => 0],

            ]);
        }
    }
}
